AWSTemplateFormatVersion: 2010-09-09
Description: >-
  Funciona en conjunto cocn All.YAML
Parameters:
    KeyName:
      Type: String
      Description: Nombre del KeyName Pair para entrar a las EC2's
    NameTag:
      Type: String
      Description: Nombre del tag
    Subnet:
      Type: String
      Description: Nombre de la subred a la que se asociara
    SG:
      Type: String
      Description: Nombre del grupo de seguridad
    LaData:
      Type: String
      Description: UserData de la EC2
Mappings:
  RegionMap:
    us-east-1:
      "32": "ami-6411e20d"
      "64": "ami-7a11e213"
    us-east-2:
      "64": "ami-3883a55d"
    us-west-1:
      "32": "ami-c9c7978c"
      "64": "ami-cfc7978a"
    eu-west-1:
      "32": "ami-37c2f643"
      "64": "ami-31c2f645"
    ap-southeast-1:
      "32": "ami-66f28c34"
      "64": "ami-60f28c32"
    ap-northeast-1:
      "32": "ami-9c03a89d"
      "64": "ami-a003a8a1"
Resources:
  EC2:
    Type: 'AWS::EC2::Instance'
    Properties:
      SubnetId: !Ref Subnet
      InstanceType: t2.micro
      KeyName: !Ref KeyName
      ImageId: !FindInMap [RegionMap, !Ref "AWS::Region", 64]
      SecurityGroupIds:
        - !Ref SG
      Tags:
        - Key: Name
          Value: !Ref NameTag
      UserData:
        Fn::Base64: !Ref LaData
Outputs:
  InstanceID:
    Description: ID de la instancia
    Value: !Ref EC2
